{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "0ebfe9fc-d98a-4531-a302-6199f8bdbe83",
   "metadata": {},
   "outputs": [],
   "source": [
    "# streamlit_app.py\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import datetime as dt\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "# ================================\n",
    "# Load the trained model\n",
    "# ================================\n",
    "best_model = joblib.load(\"calibrated_random_forest.pkl\")\n",
    "\n",
    "# ================================\n",
    "# Helper functions\n",
    "# ================================\n",
    "def calculate_age_r_lmp(dob, lmp_date):\n",
    "    \"\"\"Calculate age at last menstrual period (in years).\"\"\"\n",
    "    return lmp_date.year - dob.year - ((lmp_date.month, lmp_date.day) < (dob.month, dob.day))\n",
    "\n",
    "def calculate_p_stress(control, confid, yourway, overcome):\n",
    "    \"\"\"Perceived stress = sum of the 4 stress-related items.\"\"\"\n",
    "    return control + confid + yourway + overcome\n",
    "\n",
    "# ================================\n",
    "# Streamlit UI\n",
    "# ================================\n",
    "st.set_page_config(page_title=\"Depression Risk Classifier\", layout=\"centered\")\n",
    "st.title(\"🧠 Depression Risk Classifier (Post-Menopausal Women)\")\n",
    "st.write(\n",
    "    \"Answer the questions below. The system will compute your risk of depression \"\n",
    "    \"based on key lifestyle, health, and psychosocial factors.\"\n",
    ")\n",
    "\n",
    "# ---- Section 0: Demographics ----\n",
    "st.subheader(\"Demographics\")\n",
    "dob = st.date_input(\"Please enter your date of birth:\")\n",
    "lmp_date = st.date_input(\"What was the date of your last menstrual period?\")\n",
    "\n",
    "# ---- Section 1: Symptoms ----\n",
    "st.subheader(\"Symptoms (past two weeks)\")\n",
    "diffislp = st.radio(\"Difficulty sleeping?\", [\"No\", \"Yes\"])\n",
    "nisweat = st.radio(\"Night sweats?\", [\"No\", \"Yes\"])\n",
    "tense = st.radio(\"Feeling tense or nervous?\", [\"No\", \"Yes\"])\n",
    "irritab = st.radio(\"Irritability or grouchiness?\", [\"No\", \"Yes\"])\n",
    "\n",
    "# ---- Section 2: Perceived Stress Scale ----\n",
    "st.subheader(\"Perceived Stress (past two weeks)\")\n",
    "scale_labels = {\n",
    "    1: \"Never\", 2: \"Almost Never\", 3: \"Sometimes\", 4: \"Fairly Often\", 5: \"Very Often\"\n",
    "}\n",
    "control = st.selectbox(\"Felt unable to control important things in your life?\", list(scale_labels.values()))\n",
    "confid = st.selectbox(\"Felt confident about your ability to handle your personal problems?\", list(scale_labels.values()))\n",
    "yourway = st.selectbox(\"Felt things were going your way?\", list(scale_labels.values()))\n",
    "overcome = st.selectbox(\"Felt difficulties piling so high that you could not overcome them?\", list(scale_labels.values()))\n",
    "\n",
    "# ---- Section 3: Lifestyle ----\n",
    "st.subheader(\"Lifestyle\")\n",
    "smoke_r = st.radio(\"Do you currently smoke cigarettes?\", [\"No\", \"Yes\"])\n",
    "\n",
    "# ---- Section 4: Health ----\n",
    "st.subheader(\"Overall Health\")\n",
    "health_map = {\"Excellent\": 1, \"Very Good\": 2, \"Good\": 3, \"Fair\": 4, \"Poor\": 5}\n",
    "health = st.selectbox(\"Would you say your health in general is:\", list(health_map.keys()))\n",
    "\n",
    "# ================================\n",
    "# Prediction\n",
    "# ================================\n",
    "if st.button(\"🔍 Predict Risk\"):\n",
    "    try:\n",
    "        # Binary yes/no -> numeric\n",
    "        diffislp_val = 2 if diffislp == \"Yes\" else 1\n",
    "        nisweat_val = 2 if nisweat == \"Yes\" else 1\n",
    "        tense_val = 2 if tense == \"Yes\" else 1\n",
    "        irritab_val = 2 if irritab == \"Yes\" else 1\n",
    "        smoke_val = 2 if smoke_r == \"Yes\" else 1\n",
    "        health_val = health_map[health]\n",
    "\n",
    "        # Map Likert scales back to numeric\n",
    "        scale_reverse = {v: k for k, v in scale_labels.items()}\n",
    "        control_val = scale_reverse[control]\n",
    "        confid_val = scale_reverse[confid]\n",
    "        yourway_val = scale_reverse[yourway]\n",
    "        overcome_val = scale_reverse[overcome]\n",
    "\n",
    "        # Derived features\n",
    "        p_stress = calculate_p_stress(control_val, confid_val, yourway_val, overcome_val)\n",
    "        age_r_lmp = calculate_age_r_lmp(dob, lmp_date)\n",
    "\n",
    "        # Assemble input dataframe\n",
    "        input_data = pd.DataFrame([{\n",
    "            \"TENSE\": tense_val,\n",
    "            \"IRRITAB\": irritab_val,\n",
    "            \"CONTROL\": control_val,\n",
    "            \"P_STRESS\": p_stress,\n",
    "            \"YOURWAY\": yourway_val,\n",
    "            \"NISWEAT\": nisweat_val,\n",
    "            \"AGE_R_LMP\": age_r_lmp,\n",
    "            \"SMOKE_R\": smoke_val,\n",
    "            \"DIFFISLP\": diffislp_val,\n",
    "            \"HEALTH\": health_val\n",
    "        }])\n",
    "\n",
    "        # Prediction\n",
    "        prob = best_model.predict_proba(input_data)[:, 1][0]\n",
    "        pred = (prob >= 0.34).astype(int)  # tuned threshold\n",
    "\n",
    "        # ---- Results ----\n",
    "        st.subheader(\"Results\")\n",
    "        st.write(f\"**Predicted Risk Probability:** {prob:.2f}\")\n",
    "\n",
    "        if pred == 1:\n",
    "            st.error(\"⚠️ This person is **at risk for depression**.\")\n",
    "        else:\n",
    "            st.success(\"✅ This person is **not at high risk for depression**.\")\n",
    "\n",
    "        # ---- Risk Gauge Visualization ----\n",
    "        fig = go.Figure(go.Indicator(\n",
    "            mode=\"gauge+number\",\n",
    "            value=prob * 100,\n",
    "            title={\"text\": \"Depression Risk (%)\"},\n",
    "            gauge={\n",
    "                \"axis\": {\"range\": [0, 100]},\n",
    "                \"bar\": {\"color\": \"darkblue\"},\n",
    "                \"steps\": [\n",
    "                    {\"range\": [0, 30], \"color\": \"lightgreen\"},\n",
    "                    {\"range\": [30, 60], \"color\": \"yellow\"},\n",
    "                    {\"range\": [60, 100], \"color\": \"red\"},\n",
    "                ],\n",
    "            }\n",
    "        ))\n",
    "        st.plotly_chart(fig)\n",
    "\n",
    "    except Exception as e:\n",
    "        st.error(f\"Error processing input: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a953c526-ac68-4f3d-9732-64ce89237bbc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
